// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goxplrcpxejwgjuvphxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdveHBscmNweGVqd2dqdXZwaHhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTgzNTgsImV4cCI6MjA2ODgzNDM1OH0.xVbukrDR52ZfnXT7k1NxvqNB7zrwNEPvuWUEW_QEhF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});